Adiciona implementação para pegar RG, nome e placa
Oliveira-Everton/Avaliador-de-multas pull request #2
Opened 2022-12-01 04:25 UTC by Bi0hazard

## Motivação
O programa deve pegar o RG, nome e placa do arquivo CSV.

## Solução proposta
Varrer o arquivo CSV através de um loop e retorna na tela.

2022-12-02 22:45 UTC, gustavo-batista requested changes
Encontrei alguns problemas no PR, qualquer duvida só comentar ou me chamar!

NOTA: Seria legal se o PR #4 fosse um que remove o `__pycache__` ao invés de outra tarefa, o que acha?

2022-12-02 22:45 UTC, gustavo-batista commented on penalty_calculate/managers/file_manager.py
> +        for line, column in self._open_file():
Esse loop eh igual ao que [pega os nomes](https://github.com/Bi0hazard/Avaliador-de-multas/blob/1aba755f817265a1ca529575a17a2793b8a697f3/penalty_calculate/managers/file_manager.py#L21). O arquivo está sendo aberto 2 vezes também. Que tal simplificar em apenas um loop?

2022-12-02 22:45 UTC, gustavo-batista commented on test/integration/test_integration.py
> +        file = FileManager("Transit Ticket input 1.csv")
Nossa classe principal do programa não é o `FileManager`, temos que fazer o `PenaltyCalculate` de fato ser chamado e rodar o programa, assim transformando esse teste em um teste de integração

2022-12-02 22:45 UTC, gustavo-batista commented on test/unit/test_file_manager.py
> +class TestFileManager(unittest.TestCase):
Essa classe possui 3 métodos públicos, mas apenas 2 estão sendo testados, acredito que faltaram testes aqui, o que acha?

2022-12-02 22:45 UTC, gustavo-batista commented on penalty_calculate/managers/file_manager.py
> +        return national_number_and_name_identity_cards
Que tal usar um modelo de dados para representar as saídas dessa classe?

Retornar listas de strings dentro de uma lista não faz muito sentido para nos, afinal não são um monte de strings soltas e sim strings que possuem um valor e são específicas, o que acha?

2022-12-02 22:45 UTC, gustavo-batista commented on penalty_calculate/managers/file_manager.py
> +class FileManager:
`FileManager` nos faz pensar que o arquivo está sendo gerenciado, mas estamos apenas lendo o arquivo e formatando os conteúdos dele, que tal renomear para `Reader` ou `Parser`?

`FileManager` também eh um nome genérico, nos faz entender que eh uma classe super genérica, mas na realidade ela não lê qualquer arquivo, ela lê um arquivo especifico que contem as multas de transito junto com as informacoes do motorista, o que acha?

2022-12-28 20:15 UTC, gustavo-batista commented on penalty_calculate/managers/file_manager.py
> +        for line, column in self._open_file():
Testing comment

2022-12-28 20:22 UTC, Oliveira-Everton commented on penalty_calculate/managers/file_manager.py
> +class FileManager:
É verdade, FileManager agora se chama FileParser

2022-12-28 20:22 UTC, Bi0hazard commented on penalty_calculate/managers/file_manager.py
> +        for line, column in self._open_file():
Simplifiquei em apenas um loop!

2022-12-28 20:22 UTC, Bi0hazard commented on test/integration/test_integration.py
> +        file = FileManager("Transit Ticket input 1.csv")
Agora o PenaltyCalculate é chamado como o principal do projeto!

2022-12-28 20:22 UTC, Bi0hazard commented on test/unit/test_file_manager.py
> +class TestFileManager(unittest.TestCase):
Agora todos os métodos públicos foram testados!

2022-12-28 20:22 UTC, Bi0hazard commented on penalty_calculate/managers/file_manager.py
> +        return national_number_and_name_identity_cards
Agora as saídas das classes são representadas por modelo de dados.

2022-12-28 20:23 UTC, Bi0hazard commented on penalty_calculate/managers/file_manager.py
> +        for line, column in self._open_file():
plínio

2022-12-28 20:57 UTC, gustavo-batista requested changes

2022-12-28 20:57 UTC, gustavo-batista commented on penalty_calculate/models/identity_card.py
> +        self._id_number = id_number
Vi que a propriedade vc chama apenas de `number` e isso eh bem simples e legivel, pq o atributo ficou com o nome `id_number` que eh mais complexo e dificil de entender?

O mesmo vale pro `name`

2022-12-28 20:57 UTC, gustavo-batista commented on penalty_calculate/models/license_plate.py
> +        self._plate_car = plate_car
Aqui tambem o nome do attributo eh mais complexo que o da propriedade propriedade

2022-12-28 20:57 UTC, gustavo-batista commented on penalty_calculate/models/traffic_violation.py
> +    def __init__(self, models_id=[], license_plates=[]):
Atualmente no codigo uma infracao de transito tem apenas um identity card e uma placa, nao entendi pq ele recebe uma lista.

2022-12-28 20:57 UTC, gustavo-batista commented on test/integration/test_integration.py
> +class TestIntegration(unittest.TestCase):
Esse teste quebra ao rodar, output:
```
python -m unittest
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
/code/Avaliador-de-multas # python -m unittest
E.....E.
======================================================================
ERROR: test_penalty_calculate (test.integration.test_integration.TestIntegration.test_penalty_calculate)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/code/Avaliador-de-multas/test/integration/test_integration.py", line 11, in test_penalty_calculate
    national_id_cards_with_license_plate = penalty_calculate.csv_reader()
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/Avaliador-de-multas/penalty_calculate/penalty_calculate.py", line 10, in csv_reader
    file_parser = FileParser(self._csv_file)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/Avaliador-de-multas/penalty_calculate/parsers/file_parser.py", line 17, in __init__
    self._csv_file = self._open_file()
                     ^^^^^^^^^^^^^^^^^
  File "/code/Avaliador-de-multas/penalty_calculate/parsers/file_parser.py", line 20, in _open_file
    with open(self._file_name, mode="r") as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'Transit Ticket input 1.csv'

======================================================================
ERROR: test_output_file (test.unit.parsers.test_file_parser.TestFileParser.test_output_file)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/code/Avaliador-de-multas/test/unit/parsers/test_file_parser.py", line 9, in test_output_file
    csv_parser = FileParser("Transit Ticket input 1.csv")
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/Avaliador-de-multas/penalty_calculate/parsers/file_parser.py", line 17, in __init__
    self._csv_file = self._open_file()
                     ^^^^^^^^^^^^^^^^^
  File "/code/Avaliador-de-multas/penalty_calculate/parsers/file_parser.py", line 20, in _open_file
    with open(self._file_name, mode="r") as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'Transit Ticket input 1.csv'

----------------------------------------------------------------------
Ran 8 tests in 0.007s

FAILED (errors=2)
```

2022-12-28 20:57 UTC, gustavo-batista commented on penalty_calculate/parsers/file_parser.py
> +    _LICENSE_PLATE = 0
Gostei da ideia de colocar cada indice em constant nice!

2022-12-28 20:57 UTC, gustavo-batista commented on penalty_calculate/parsers/file_parser.py
> +        list_models_id = []
Esse nome eh um pouco confuso, pq nao cololcar o nome da variavel que vc quer + um `s` de plural?
Exemplo uma lista que possui varios `Dog` se chamaria `dogs`, uma lista que contem varias `House` se chamaria `houses` e uma lista que contem int se chamaria `integers` e/ou `numbers`. O que acha?

2022-12-28 20:57 UTC, gustavo-batista commented on penalty_calculate/parsers/file_parser.py
> +    def _organize_models(self):
O nome desse metodo nao nos diz muito o que ele faz, que tal `build_` + `algum nome que faz sentido`? jah que ele constroi os modelos e nao organiza models ja existentes?

2022-12-28 20:57 UTC, gustavo-batista commented on penalty_calculate/parsers/file_parser.py
> +            models_id=self._models_id_cards,
TrafficViolation eh referente a uma violacao de transito, pq ele ta recebendo uma lista de RGs e placas?

Outro ponto, uma placa especifica tem relacao com um RG especifico, mas um RG qualquer nao tem relacao com todas as outras placas.

2022-12-28 20:57 UTC, gustavo-batista commented on penalty_calculate/serializers/output_serializer.py
> +        self._model = traffic_violation_model
O nome desse atributo tah muito generico `_model`, quje tal mudar pra algo mais espefico?

2022-12-28 20:57 UTC, gustavo-batista commented on penalty_calculate/serializers/output_serializer.py
> +    def _output_id(self):
Tenta nao usar abreviacoes quando possivel, sempre prefira ser explicito.

2022-12-29 18:08 UTC, Bi0hazard commented on test/integration/test_integration.py
> +class TestIntegration(unittest.TestCase):
O arquivo usado no teste agora será commitado junto!

2022-12-29 18:16 UTC, Bi0hazard commented on penalty_calculate/parsers/file_parser.py
> +        list_models_id = []
Faz sentido!

2022-12-29 18:16 UTC, Bi0hazard commented on penalty_calculate/parsers/file_parser.py
> +    def _organize_models(self):
Perfeita sugestão!

2023-01-06 02:13 UTC, gustavo-batista requested changes

2023-01-06 02:13 UTC, gustavo-batista commented on penalty_calculate/models/identity_card.py
> +    def __init__(self, number='', name=''):
No seu codigo vc nunca inicializa um IdentityCard sem argumentos, mas aqui vc definiu "default values", acho que ficaria mais semantico sem, o que acha?

2023-01-06 02:13 UTC, gustavo-batista commented on penalty_calculate/parsers/file_parser.py
> +        self._file_name = file_name
`file_name` eh usado apenas no metodo `_serialize_file`, pq nao passar o parametro diretamente para ele ao inves de atribuir um atributo?

2023-01-06 02:13 UTC, gustavo-batista commented on penalty_calculate/models/traffic_violations.py
> +class TrafficViolations:
Existe algum motivo para essa classe existir e nao ser apenas uma lista? Vc nao adicionou nenhum comportamento nela.

2023-01-06 02:13 UTC, gustavo-batista commented on penalty_calculate/parsers/file_parser.py
> +            reader_csv = csv.reader(file, delimiter=";")
Magical string `";"`

2023-01-06 02:13 UTC, gustavo-batista commented on penalty_calculate/serializers/output_serializer.py
> +                f'{violation.id_card.number}; {violation.id_card.name}'
Que tal usar um format nessa string? pois ela ta um pouco magica

2023-01-09 22:31 UTC, Bi0hazard commented on penalty_calculate/models/identity_card.py
> +    def __init__(self, number='', name=''):
Retirei os "default values"!

2023-01-09 22:32 UTC, Bi0hazard reviewed
Alterei bastante o código, gostaria que desse uma olhadinha!

2023-01-09 22:35 UTC, Oliveira-Everton commented on penalty_calculate/models/traffic_violations.py
> +class TrafficViolations:
Na verdade não, agora ela é uma lista!

2023-01-09 22:35 UTC, Oliveira-Everton commented on penalty_calculate/parsers/file_parser.py
> +        self._file_name = file_name
Agora o file_name é passado diretamente como parâmetro

2023-01-09 22:35 UTC, Oliveira-Everton commented on penalty_calculate/parsers/file_parser.py
> +            reader_csv = csv.reader(file, delimiter=";")
No more Magica

2023-01-09 22:35 UTC, Oliveira-Everton commented on penalty_calculate/serializers/output_serializer.py
> +                f'{violation.id_card.number}; {violation.id_card.name}'
Utilizei!

2023-01-11 01:26 UTC, gustavo-batista requested changes

2023-01-11 01:26 UTC, gustavo-batista commented on penalty_calculate/parsers/file_parser.py
> +    _LICENSE_PLATE = _FIRST_LINE = 0
Aqui da a ideia que `_LICENSE_PLATE` e `_FIRST_LINE` sao relacionados, mas na verdade sao duas informacoes distintas, que tal separa-los?

2023-01-11 01:26 UTC, gustavo-batista commented on penalty_calculate/parsers/file_parser.py
> +    _SEMICOLON = ';'
Ao inves de descrever o que eh essa variavel e/ou o proposito vc descreveu qual o valor dela, que tal alterar o nome?

2023-01-11 01:26 UTC, gustavo-batista commented on penalty_calculate/parsers/file_parser.py
> +        self._csv_file = self._convert_file(file_name)
Esse construtor pode dar erro, nao eh uma boa pratica um objeto quebrar na hora de ser instanciado, que tal apenas atribuir o `file_name` e deixar o que eh perigoso pra depois.

2023-01-11 01:26 UTC, gustavo-batista commented on penalty_calculate/penalty_calculate.py
> +    def __init__(self, csv_file):
[Aqui](https://github.com/Bi0hazard/Avaliador-de-multas/blob/2325aa1a4b9ba7ac6933ea02259190f818cbf182/penalty_calculate/parsers/file_parser.py#L16) o nome ficou bem legal, mas nessa linha acabou ficando com o nome antigo.

2023-01-11 01:26 UTC, gustavo-batista commented on penalty_calculate/serializers/output_serializer.py
> +    def _output_identity_cards(self, traffic_violations):
Que tal colocar o construtor para apenas atribuir o traffic_violations e renomear esse metodo como output? Assim teremos um metodo a menos e o contrutor fica com pouca logica, o que acha?

2023-01-11 01:26 UTC, gustavo-batista commented on penalty_calculate/serializers/output_serializer.py
> +                    violation.identity_card.name,
Aqui vc acaba repetindo o `violation.identity_card` que tal criar uma propriedade para isso?

2023-01-11 01:26 UTC, gustavo-batista commented on test/unit/parsers/test_file_parser.py
> +        violations_to_compare = [
Aqui eh o lugar do `setup`, que tal colocar no bloco das `expectation`s

2023-01-11 01:26 UTC, gustavo-batista commented on test/unit/parsers/test_file_parser.py
> +                    name="Josevaldo Cal. O. Teiro", number="467191153"
Aqui vc comecou a quebrar a linha, mas nao quebrou os parametros, que tal quebrar depois da `,` aqui?

2023-01-11 23:03 UTC, Oliveira-Everton commented on penalty_calculate/parsers/file_parser.py
> +    _LICENSE_PLATE = _FIRST_LINE = 0
É verdade!

2023-01-11 23:03 UTC, Oliveira-Everton commented on penalty_calculate/parsers/file_parser.py
> +    _SEMICOLON = ';'
Certo!

2023-01-11 23:03 UTC, Oliveira-Everton commented on penalty_calculate/parsers/file_parser.py
> +        self._csv_file = self._convert_file(file_name)
Feito! O construtor apenas atribui o 'file_name'.

2023-01-11 23:03 UTC, Oliveira-Everton commented on penalty_calculate/penalty_calculate.py
> +    def __init__(self, csv_file):
Verdade, não tinha notado!

2023-01-11 23:03 UTC, Bi0hazard commented on penalty_calculate/serializers/output_serializer.py
> +    def _output_identity_cards(self, traffic_violations):
Feito, o que acha de como está agora?

2023-01-11 23:16 UTC, Bi0hazard commented on test/unit/parsers/test_file_parser.py
> +        violations_to_compare = [
Feito!

2023-01-11 23:16 UTC, Bi0hazard commented on test/unit/parsers/test_file_parser.py
> +                    name="Josevaldo Cal. O. Teiro", number="467191153"
Feito!

2023-01-27 21:58 UTC, gustavo-batista requested changes

2023-01-27 21:58 UTC, gustavo-batista commented on penalty_calculate/parsers/file_parser.py
> +    def traffic_violations(self):
Essa funcao aqui nao ta fazendo nada alem de chamar outra funcao, que tal deleta-la e chamar a `_build_traffic_violation_models` de `traffic_violations`?

Outra coisa, lembra que metodos devem ter verbos, esse aqui nao tem verbo, que tal adicionar um verbo ao nome?

2023-01-27 21:58 UTC, gustavo-batista commented on penalty_calculate/serializers/output_serializer.py
> +    def output_string(self):
Mesmo comentario adicionado ao `penalty_calculate/parsers/file_parser.py`, funcao nao faz nada alem de chamar outra.

2023-01-27 21:58 UTC, gustavo-batista commented on test/unit/models/test_traffic_violation.py
> +    def test_property_model_plate(self):
Esse nome nao ta de acordo com os outros ja definidos certo? Que tal mudar para padronizar?

2023-01-27 21:58 UTC, gustavo-batista commented on test/unit/models/test_identity_card.py
> +    def test_property_identity_name(self):
Esse nome nao ta de acordo com os outros ja definidos em outros arquivos. Que tal mudar para padronizar?

2023-01-27 21:58 UTC, gustavo-batista commented on test/unit/models/test_identity_card.py
> +    def test_property_identity_number(self):
Mesmo comentario sobre `test_property_identity_name`

2023-01-27 21:58 UTC, gustavo-batista commented on penalty_calculate/serializers/output_serializer.py
> +    def _output_identity_cards(self, traffic_violations):
Boa isso mesmo

2023-01-27 21:58 UTC, gustavo-batista commented on test/integration/test_integration.py
> +class TestIntegration(unittest.TestCase):
Agora sim!

2023-01-27 21:59 UTC, gustavo-batista commented
Os testes quebraram por outro motivo agora, output:
```pyhton
/code/Avaliador-de-multas # pipenv run python -m unittest
....E..E.                                                      
======================================================================
ERROR: test_property_model_plate (test.unit.models.test_traffic_violation.TestTrafficViolation.test_property_model_plate)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/code/Avaliador-de-multas/test/unit/models/test_traffic_violation.py", line 35, in test_property_model_plate
    license_plate = traffic_violation.license_plate
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TrafficViolation' object has no attribute 'license_plate'

======================================================================
ERROR: test_traffic_violations (test.unit.parsers.test_file_parser.TestFileParser.test_traffic_violations)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/code/Avaliador-de-multas/test/unit/parsers/test_file_parser.py", line 15, in test_traffic_violations
    self.assertEqual(
  File "/usr/local/lib/python3.11/unittest/case.py", line 873, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/local/lib/python3.11/unittest/case.py", line 1079, in assertListEqual
    self.assertSequenceEqual(list1, list2, msg, seq_type=list)
  File "/usr/local/lib/python3.11/unittest/case.py", line 1004, in assertSequenceEqual
    if seq1 == seq2:
       ^^^^^^^^^^^^
  File "/code/Avaliador-de-multas/penalty_calculate/models/traffic_violation.py", line 21, in __eq__
    self.license_plate == other.license_plate
    ^^^^^^^^^^^^^^^^^^
AttributeError: 'TrafficViolation' object has no attribute 'license_plate'

----------------------------------------------------------------------
Ran 9 tests in 0.007s

FAILED (errors=2)
```

2023-01-27 22:00 UTC, gustavo-batista reviewed
Os testes quebraram por outro motivo agora, output:
```pyhton
/code/Avaliador-de-multas # pipenv run python -m unittest
....E..E.                                                      
======================================================================
ERROR: test_property_model_plate (test.unit.models.test_traffic_violation.TestTrafficViolation.test_property_model_plate)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/code/Avaliador-de-multas/test/unit/models/test_traffic_violation.py", line 35, in test_property_model_plate
    license_plate = traffic_violation.license_plate
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TrafficViolation' object has no attribute 'license_plate'

======================================================================
ERROR: test_traffic_violations (test.unit.parsers.test_file_parser.TestFileParser.test_traffic_violations)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/code/Avaliador-de-multas/test/unit/parsers/test_file_parser.py", line 15, in test_traffic_violations
    self.assertEqual(
  File "/usr/local/lib/python3.11/unittest/case.py", line 873, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/local/lib/python3.11/unittest/case.py", line 1079, in assertListEqual
    self.assertSequenceEqual(list1, list2, msg, seq_type=list)
  File "/usr/local/lib/python3.11/unittest/case.py", line 1004, in assertSequenceEqual
    if seq1 == seq2:
       ^^^^^^^^^^^^
  File "/code/Avaliador-de-multas/penalty_calculate/models/traffic_violation.py", line 21, in __eq__
    self.license_plate == other.license_plate
    ^^^^^^^^^^^^^^^^^^
AttributeError: 'TrafficViolation' object has no attribute 'license_plate'

----------------------------------------------------------------------
Ran 9 tests in 0.007s

FAILED (errors=2)
```

2023-04-13 22:24 UTC, gustavo-batista commented
Percebi que os ultimos commits https://github.com/Oliveira-Everton/Avaliador-de-multas/pull/2/commits/14f67f6fa4fdc5efe1d6691c0e5cf89560cf2df3, https://github.com/Oliveira-Everton/Avaliador-de-multas/pull/2/commits/25b42b865eb6e4972d5126c18b4202977a005fde, https://github.com/Oliveira-Everton/Avaliador-de-multas/pull/2/commits/2285051f0431399de6a9bd95c43ddb9df855332a, https://github.com/Oliveira-Everton/Avaliador-de-multas/pull/2/commits/d54a4bebd707d9a21557105fc122688c6f8dc9c2 e https://github.com/Oliveira-Everton/Avaliador-de-multas/pull/2/commits/739f512b3f33541d41ef3bf8127bf417ec61a629 fogem a proposta inicial desse PR que se encontra na "Motivação".

Esses commits foram colocados aqui por engano?

2023-04-17 18:25 UTC, Oliveira-Everton commented
Sim, os últimos commits foram feitos por engano neste Pull Request.

2023-04-18 01:28 UTC, gustavo-batista approved these changes
LGTM (Looks Good To Me)

2023-04-18 17:56 UTC, merged