Adiciona métodos para agrupar os dados dos infratores
Oliveira-Everton/Avaliador-de-multas pull request #5
Opened 2023-05-31 19:26 UTC by Oliveira-Everton

## Motivação

Precisamos agrupar os dados repetidos dos infratores.

## Solução Proposta
Adicionar um manager que recebe uma lista de infrações, analisa cada uma e gera uma nova lista agrupando os infratores a partir do seu número de RG. No caso das placas que correspondem ao mesmo RG, é gerada uma nova lista apenas pra elas onde só é adicionada uma nova placa se ela não for repetida. 

Adicionar um novo método ao `OutputSerializer` que desempacota as placas para poder mostrar o texto sem aspas, nem colchetes. Para isso o método vai copiar o texto que contém esses caracteres e gerar um novo texto sem eles.

2023-06-01 23:39 UTC, gustavo-batista requested changes

2023-06-01 23:39 UTC, gustavo-batista commented on test/unit/serializers/test_output_serializer.py
> +            license_plates=LicensePlates('IDE-3516')
Acredito que seria bom padronizar as strings, aqui vc colocou a placa como `'`, mas em outros lugares no codigo temos ela como `'`. [PEP8](https://peps.python.org/pep-0008/#string-quotes)

Uma convencao que sigo eh essa aqui: https://docs.ckan.org/en/ckan-2.1.5/python-coding-standards.html#use-single-quotes

2023-06-01 23:39 UTC, gustavo-batista commented on main_penalty_calculate/managers/violations_manager.py
> +    def _agroupes_violators_avaliations(self):
O verbo deveria ser um [verbo imperativo](https://conjugator.reverso.net/conjugation-english-verb-chart.html)

2023-06-01 23:39 UTC, gustavo-batista commented on main_penalty_calculate/managers/violations_manager.py
> +    def _agroupes_violators_avaliations(self):
Tem uma forma melhor de fazer isso aqui, esse metodo ta super complexo, se vc quebrar em mais metodos nao publicos vai ficar mais isolado e facil de ver uma melhor solucao ;)

2023-06-01 23:39 UTC, gustavo-batista commented on main_penalty_calculate/models/traffic_violation.py
> +    def _compare_properties(self, traffic_violation):
O nome do metodo nao reflete o que ele retorna, nao eh mesmo?

2023-06-01 23:39 UTC, gustavo-batista commented on main_penalty_calculate/models/traffic_violation.py
> +    def _compare_properties(self, traffic_violation):
Esse metodo comete uma falha grave, possui argumentos nao utilizados

2023-06-01 23:39 UTC, gustavo-batista commented on main_penalty_calculate/models/violator_avaliation.py
> +    def _compare_properties(self, violator_avaliation):
Mesmo comentarios do `main_penalty_calculate/models/traffic_violation.py`

2023-06-01 23:39 UTC, gustavo-batista commented on main_penalty_calculate/penalty_calculate.py
> +    def _csv_reader(self):
Isso nao eh um leitor de CSV, que tal renomear pra um nome que faca mais sentido?

2023-06-01 23:39 UTC, gustavo-batista commented on main_penalty_calculate/managers/violations_manager.py
> +class ViolationsManager:
No que pensou quando decidiu o nome dessa classe? "gerenciador de violacoes" me parece um pouco estranho pelo que ela ta fazendo, o que acha?

2023-06-01 23:39 UTC, gustavo-batista commented on main_penalty_calculate/serializers/output_serializer.py
> +                    self._unpacks_list(
O python jah possui uma forma melhor de fazer isso aqui, que tal dar uma consultada na documentacao de strings do python? https://docs.python.org/3/library/stdtypes.html#string-methods

2023-06-01 23:41 UTC, gustavo-batista commented on main_penalty_calculate/models/license_plates.py
> +class LicensePlates:
Essa classe engloba uma lista de strings, mas nao adiciona nenhum comportamento, algum motivo pra ela exisitr?

2023-06-09 22:44 UTC, Oliveira-Everton commented
Fiz alterações nas áreas que você pontuou! O que acha?

2023-06-13 19:44 UTC, gustavo-batista requested changes

2023-06-13 19:44 UTC, gustavo-batista commented on main_penalty_calculate/builders/violators_avaliations_builder.py
> +    def _search_identity_card_number(
O nome desse metodo nao condiz com o que ta sendo retornado, que tal deixar num padrao parecido com o que o python usa para metodos boolean? https://docs.python.org/3/library/stdtypes.html#str.isalnum

Esse metodo ficaria `is_identity_already_present` ou algo parecido.

2023-06-13 19:44 UTC, gustavo-batista commented on main_penalty_calculate/models/violator_avaliation.py
> +    def _properties_value_list(self, violator_avaliation):
Aqui ficaria mais elegante se tivesse apenas no plural `_properties_values` igual vc fez em outras variaveis do tipo lista

2023-06-13 19:44 UTC, gustavo-batista commented on main_penalty_calculate/models/violator_avaliation.py
> +    def _properties_value_list(self, violator_avaliation):
Esse metodo tem um problema, possui uma variavel que nao ta sendo usada: `self`

2023-06-13 19:44 UTC, gustavo-batista commented on main_penalty_calculate/penalty_calculate.py
> +    def evaluates_infractors(self):
O tempo verbal desse verbo ta incorreto, deveria ser um [verbo imperativo](https://conjugator.reverso.net/conjugation-english-verb-chart.html)

2023-06-13 19:44 UTC, gustavo-batista commented on main_penalty_calculate/serializers/output_serializer.py
> +    _PATTERN_FOR_REGEX = r'\[|\]|\''
Nome bem descritivo, nice!

2023-06-13 19:44 UTC, gustavo-batista commented on test/unit/models/test_violator_avaliation.py
> +    def test_violator_avaliation_check_plates(self):
O nome do teste nao ta no padrao onde nos diz o que ta sendo testado. nao existe metodo `check_plates`

2023-06-13 19:44 UTC, gustavo-batista commented on test/unit/parsers/test_file_parser.py
> +        converted_file = csv_parser.convert_file()
O nome do teste nao ta no padrao onde nos diz o que ta sendo testado. nao existe metodo `build_traffic_violations`

2023-06-13 19:44 UTC, gustavo-batista commented on test/integration/test_integration.py
>      def test_penalty_calculate_csv_reader(self):
Seria legal um nome mais legal de que cenario ta sendo testado nesse teste de integracao

2023-06-13 19:44 UTC, gustavo-batista commented on main_penalty_calculate/builders/violators_avaliations_builder.py
> +    def _search_license_plate_number(
O mesmo que comentei no metodo `_search_identity_card_number` vale pra esse tambem.

2023-06-13 19:44 UTC, gustavo-batista commented on main_penalty_calculate/serializers/output_serializer.py
> +    def output_string(
A identacao desse metodo ta estranho, deveria estar tudo na mesma linha `def output_string(self):`, isso acontece no projeto inteiro, varias quebras de linhas desnecessarias que nao atingiriam o maximo de 79 linhas.

2023-06-13 19:44 UTC, gustavo-batista commented on test/unit/builders/test_violators_avaliations_builder.py
> +class TestViolatorsAvaliationsBuilder(unittest.TestCase):
Essa classe precisa de mais testes, cade o teste de agregacao de placas? Se vc consegue remover linhas de codigo e o teste continua passando isso quer dizer que o teste nao ta completo.

2023-06-13 19:44 UTC, gustavo-batista commented on main_penalty_calculate/models/traffic_violation.py
> +    def type_infraction(self):
Essa propriedade nao ta sendo usada em nenhum lugar, alem de nao fazer parte da proposta desse PR.

2023-06-13 19:44 UTC, gustavo-batista commented on main_penalty_calculate/models/traffic_violation.py
> +    def infraction_date(self):
Mesmo comentario da `def type_infraction(self)`

2023-06-13 19:44 UTC, gustavo-batista commented on main_penalty_calculate/models/traffic_violation.py
> +    def notification_date(self):
Mesmo comentario da `def type_infraction(self)`

2023-06-13 19:44 UTC, gustavo-batista commented on main_penalty_calculate/models/traffic_violation.py
> +    def pay_date(self):
Mesmo comentario da `def type_infraction(self)`

2023-06-13 19:44 UTC, gustavo-batista commented on main_penalty_calculate/models/traffic_violation.py
> +        self._pay_date = pay_date
Esses 4 atributos nao deveriam estar aqui, eles nao estao sendo usados para nada.

2023-06-13 19:44 UTC, gustavo-batista commented on main_penalty_calculate/builders/traffic_violation_builder.py
> +class TrafficViolationBuilder:
Essa classe ta sem teste nenhum

2023-06-15 22:36 UTC, gustavo-batista approved these changes
Boa pode fazer o squash e merge!

2023-06-15 23:45 UTC, Oliveira-Everton commented on main_penalty_calculate/managers/violations_manager.py
> +class ViolationsManager:
Eu pensei que Manager seria um bom nome já que a classe iria gerenciar as multas de trânsito. Porém "Builder" me parece melhor. Alterei para "construtor de avaliações dos infratores".

2023-06-15 23:45 UTC, Oliveira-Everton commented on main_penalty_calculate/models/license_plates.py
> +class LicensePlates:
Tem razão, ela era desnecessária mesmo.

2023-06-15 23:45 UTC, Oliveira-Everton commented on main_penalty_calculate/penalty_calculate.py
> +    def _csv_reader(self):
renomeado!

2023-06-15 23:45 UTC, Oliveira-Everton commented on main_penalty_calculate/models/traffic_violation.py
> +    def _compare_properties(self, traffic_violation):
Retirei os argumentos não utilizados

2023-06-15 23:45 UTC, Oliveira-Everton commented on main_penalty_calculate/models/traffic_violation.py
> +    def _compare_properties(self, traffic_violation):
Nome do método alterado, agora está de acordo com o que ele retorna

2023-06-15 23:45 UTC, Oliveira-Everton commented on test/unit/serializers/test_output_serializer.py
> +            license_plates=LicensePlates('IDE-3516')
Certo! Padronizei o uso das aspas em strings

2023-06-15 23:45 UTC, Oliveira-Everton commented on main_penalty_calculate/managers/violations_manager.py
> +    def _agroupes_violators_avaliations(self):
Corrigido!

2023-06-15 23:45 UTC, Oliveira-Everton commented on main_penalty_calculate/models/violator_avaliation.py
> +    def _compare_properties(self, violator_avaliation):
Corrigido!

2023-06-15 23:45 UTC, Oliveira-Everton commented on main_penalty_calculate/managers/violations_manager.py
> +    def _agroupes_violators_avaliations(self):
Certo. Quebrei esse método em 3 outros não públicos! ^_^

2023-06-15 23:45 UTC, Oliveira-Everton commented on main_penalty_calculate/serializers/output_serializer.py
> +                    self._unpacks_list(
Utilizei expressão regular no lugar desse método, o que acha?

2023-06-15 23:45 UTC, Oliveira-Everton commented on main_penalty_calculate/builders/violators_avaliations_builder.py
> +    def _search_identity_card_number(
Obrigado pela indicação ^^

2023-06-15 23:45 UTC, Oliveira-Everton commented on main_penalty_calculate/serializers/output_serializer.py
> +    def output_string(
Certo! Tenho uma dúvida. No caso do Penalty Calculate onde umas linhas vão atingir o limite de 79 e outras não, devo quebrar todas pelo padrão ou apenas aquelas que vão chegar ao limite?

2023-06-15 23:55 UTC, gustavo-batista commented on main_penalty_calculate/serializers/output_serializer.py
> +    def output_string(
Se vc quebrar toda linha onde o python permite concorda que todos os arquivos ficariam enormes e dificil de ler?
Uma linha com mais de 100 caracteres fica facil ou dificil de ler?

Entendeu a motivacao?

2023-06-16 01:15 UTC, merged